#!/usr/bin/env python
"""Generate the bundled TET4 cantilever demo case (``examples/cantilever/``).

Writes a small Radioss starter deck ``cantilever_0000.rad`` and a minimal
engine deck ``cantilever_0001.rad`` for a structured TET4 cantilever beam:
an ``nx x ny x nz`` node grid (default 20x6x6 -> 2850 tets) whose x=0 face is
the fixed end (its nodes form the ``/GRNOD/NODE/60000000`` BC group) and whose
x=L face carries a tip-load node group + ``/CLOAD``. Ids follow the oropt
defaults: design part id 60000000, node/element ids >= 60000000.

The deck is meant for the *demo* backend (:mod:`oropt.demo`) — it parses
cleanly through :class:`oropt.deck.Deck` and drives the whole pipeline, but it
carries no materials/controls tuned for a real OpenRadioss solve.

Purely deterministic (stdlib only, no RNG): rerunning reproduces the files
byte-for-byte. Usage, from the repo root::

    python scripts/make_demo_case.py [--out examples/cantilever]
"""
from __future__ import annotations

import argparse
from pathlib import Path

PART_ID = 60000000
BC_GROUP_ID = 60000000       # fixed-end (x=0) nodes -> model.bc_group_id default
TIP_GROUP_ID = 60000001      # loaded tip (x=lx) nodes
NODE_BASE = 60000000         # node ids start at NODE_BASE + 1 (>= design_node_min)
ELEM_BASE = 60000000         # element ids start at ELEM_BASE + 1

# 6-tet decomposition of a hex (indices into its corners n1..n8, Radioss order:
# n1-n4 bottom quad, n5-n8 top), all sharing the n1-n7 main diagonal — the same
# split oropt.deck uses for /BRICK keep-out geometry, exact for a convex hex.
HEX_TO_TETS = ((0, 1, 2, 6), (0, 2, 3, 6), (0, 3, 7, 6),
               (0, 7, 4, 6), (0, 4, 5, 6), (0, 5, 1, 6))


def build_cantilever(nx: int, ny: int, nz: int,
                     lx: float, ly: float, lz: float):
    """Nodes, tets and the fixed/tip node groups of the structured beam.

    Returns ``(nodes, tets, fixed_ids, tip_ids, tip_center_id)`` where *nodes*
    is ``[(id, x, y, z)]``, *tets* is ``[(id, n1, n2, n3, n4)]`` and
    *tip_center_id* is the node nearest the centre of the loaded face (a good
    displacement-constraint node for configs).
    """
    def nid(ix: int, iy: int, iz: int) -> int:
        return NODE_BASE + 1 + (ix * ny + iy) * nz + iz

    nodes = [(nid(ix, iy, iz),
              lx * ix / (nx - 1), ly * iy / (ny - 1), lz * iz / (nz - 1))
             for ix in range(nx) for iy in range(ny) for iz in range(nz)]

    tets, eid = [], ELEM_BASE + 1
    for ix in range(nx - 1):
        for iy in range(ny - 1):
            for iz in range(nz - 1):
                corners = (nid(ix, iy, iz), nid(ix + 1, iy, iz),
                           nid(ix + 1, iy + 1, iz), nid(ix, iy + 1, iz),
                           nid(ix, iy, iz + 1), nid(ix + 1, iy, iz + 1),
                           nid(ix + 1, iy + 1, iz + 1), nid(ix, iy + 1, iz + 1))
                for t in HEX_TO_TETS:
                    tets.append((eid,) + tuple(corners[k] for k in t))
                    eid += 1

    fixed = [nid(0, iy, iz) for iy in range(ny) for iz in range(nz)]
    tip = [nid(nx - 1, iy, iz) for iy in range(ny) for iz in range(nz)]
    tip_center = nid(nx - 1, (ny - 1) // 2, (nz - 1) // 2)
    return nodes, tets, fixed, tip, tip_center


def _group_lines(ids: list[int]) -> list[str]:
    return ["".join(f"{v:>10}" for v in ids[k:k + 10])
            for k in range(0, len(ids), 10)]


def starter_text(nodes, tets, fixed, tip) -> str:
    out = [
        "#- oropt demo case: TET4 cantilever beam "
        "(generated by scripts/make_demo_case.py)",
        "/MAT/LAW1/1",
        "aluminium",
        "#        RHO_I",
        "              2.7E-9",
        "#            E              nu",
        "         70000.             0.33",
        "/NODE",
        "#  Node ID                   X                   Y                   Z",
    ]
    out += [f"{n:>10}{x:>20.10g}{y:>20.10g}{z:>20.10g}" for n, x, y, z in nodes]
    out += [
        f"/PART/{PART_ID}",
        "cantilever_design",
        "         1         1         0",
        f"/TETRA4/{PART_ID}",
    ]
    out += ["".join(f"{v:>10}" for v in row) for row in tets]
    out += [
        "#-  PROPERTIES:",
        "/PROP/SOLID/1",
        "solid_prop",
        f"/GRNOD/NODE/{BC_GROUP_ID}",
        "fixed_end",
        *_group_lines(fixed),
        "/BCS/1",
        "fixed_end_clamp",
        "#  Tra rot   skew_ID  grnod_ID",
        f"   111 111         0{BC_GROUP_ID:>10}",
        f"/GRNOD/NODE/{TIP_GROUP_ID}",
        "tip_load_set",
        *_group_lines(tip),
        "/CLOAD/1",
        "tip_load",
        "#   fct_ID       DIR   skew_ID   sens_ID  grnod_ID",
        f"         1         Z         0         0{TIP_GROUP_ID:>10}",
        "/END",
    ]
    return "\n".join(out) + "\n"


ENGINE_TEXT = """\
/RUN/cantilever/1
                 1.0
/ANIM/DT
0. 1.0
/ANIM/ELEM/ENER
/ANIM/ELEM/VONM
/IMPL/NONLIN/1
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default="examples/cantilever",
                    help="output directory (default: examples/cantilever)")
    ap.add_argument("--nx", type=int, default=20, help="nodes along the beam")
    ap.add_argument("--ny", type=int, default=6)
    ap.add_argument("--nz", type=int, default=6)
    ap.add_argument("--lx", type=float, default=100.0, help="beam length [mm]")
    ap.add_argument("--ly", type=float, default=25.0)
    ap.add_argument("--lz", type=float, default=25.0)
    args = ap.parse_args()

    nodes, tets, fixed, tip, tip_center = build_cantilever(
        args.nx, args.ny, args.nz, args.lx, args.ly, args.lz)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    starter = out / "cantilever_0000.rad"
    engine = out / "cantilever_0001.rad"
    starter.write_text(starter_text(nodes, tets, fixed, tip),
                       encoding="utf-8", newline="\n")
    engine.write_text(ENGINE_TEXT, encoding="utf-8", newline="\n")
    print(f"wrote {starter} ({len(nodes)} nodes, {len(tets)} tets, "
          f"part {PART_ID})")
    print(f"wrote {engine}")
    print(f"BC group /GRNOD/NODE/{BC_GROUP_ID}: {len(fixed)} fixed-end nodes; "
          f"tip group /GRNOD/NODE/{TIP_GROUP_ID}: {len(tip)} nodes")
    print(f"suggested displacement-constraint node (tip centre): {tip_center}")


if __name__ == "__main__":
    main()
